### ISSUE TITLE
Help: Kernel Development [pt-br]

### ISSUE THREAD

**Issue by Jonatha-Varjao** [frednora/gramado#14]
Oi Fred,
  Então, sei que muita parte do desenvolvimento, você está codando sozinho. Queria saber se não tem como vc dispôr em algo as etapas que precisam pra galera, até eu, te ajudar.
  Seu projeto é muito bacana, vlw !

**Comment by frednora** [comment]
Tem sim ... vou escrever algumas considerações sobre o sistema que possam ser úteis para quem quer contribuir.

**Comment by Jonatha-Varjao** [comment]
Maravilha !!!, quando terminar as considerações joga o link aqui na issue e feche que, provavelmente, vai ajudar a glr que tem a mesma pergunta!
Vlw !

**Comment by frednora** [comment]
O ideal seria uma documentação ... mas é muito trabalho documentar tudo ... então vou fazendo aos poucos. Principalmente o que acho mais relevante.

**Comment by frednora** [comment]
Ahh entendi ... tipo um roteiro ?!!

**Comment by frednora** [comment]
Uma coisa é um fato ... o repositório /gde é o ambiente ideal pra maioria começar. É lá que ficam os aplicativos, a api e as bibliotecas ...

**Comment by Jonatha-Varjao** [comment]
>  Uma coisa é um fato ... o repositório /gde é o ambiente ideal pra maioria começar. é lá que ficam os aplicativos, a api e as bibliotecas ...

Tava lendo, bem consciso, e direto, muito bom, vou começar por lá
