### ISSUE TITLE
Help: Compiling

### ISSUE THREAD

**Issue by frednora** [frednora/gramado#16]
Compiling Gramado on Linux.
=======================

 Linux 5.0.21-1-MANJARO x86_64
gcc (GCC) 9.1.0
GNU ld (GNU Binutils) 2.32
NASM version 2.14.02 compiled on Jan 22 2019

**Comment by dsfb** [comment]
Hi, Fred.

I compiled the version 1.3-rc5 of the Gramado Operating System, and I stored the zipped VirtualBox's file of this version in the repo: https://github.com/dsfb/gramado-boxes
.

**Comment by frednora** [comment]
Cool. Thank you, :)

**Comment by dsfb** [comment]
You are welcome, Fred!

**Comment by xadaemon** [comment]
I might give a shot at compiling this with a pipeline if it interests you

**Comment by xadaemon** [comment]
I managed to do it in my fork octetd/gramado it was easier than expected I can open a pr if you are ok with it

**Comment by frednora** [comment]
> I might give a shot at compiling this with a pipeline if it interests you

Great, thank You! :)
