### ISSUE TITLE
Gramado's console font name?

### ISSUE THREAD

**Issue by NathanPB** [frednora/gramado#20]
Hello, I'm currently reworking [Gramado's website](https://github.com/gramado/gramado.github.io) and I wanna know the name of the font (or a next one) used in the print at README.md

Thank u
![image](https://user-images.githubusercontent.com/18128642/66173592-55da6580-e627-11e9-9202-a8c459177768.png)

**Comment by frednora** [comment]
Nathan. A fonte usada aí é uma fonte criada pelo Nelson Cole. É um protótipo e não está pronta. Chamo ela de NC2. Já as letras grandes que você está vendo não possuem fonte, é apenas um ASCII art.

**Comment by NathanPB** [comment]
> Nathan. A fonte usada aí é uma fonte criada pelo Nelson Cole. É um protótipo e não está pronta. Chamo ela de NC2. Já as letras grandes que você está vendo não possuem fonte, é apenas um ASCII art.

A ASCII art eu consegui reproduzir sem problemas. Tens algum arquivo da fonte que possa distribuir?

**Comment by frednora** [comment]
Por enquanto a fonte está num formato não convenciaonal. Estou compilando como se fosse um aplicativo. No futuro vou usar formatos tradicionais. https://github.com/frednora/gramado/tree/master/lib/fonts/nc2

**Comment by NathanPB** [comment]
Certo, obrigado
