### ISSUE TITLE
compiling: Erro ao executar make pela 1º vez

### ISSUE THREAD

**Issue by Jmallone** [frednora/gramado#23]
Toda vez que eu baixo pela primeira vez e dou um `$ make`, o terminal retorna isso:
![image](https://user-images.githubusercontent.com/6977257/100966942-d7b86e00-350c-11eb-9c83-6ef1cff46f14.png)
E no emulador:
![image](https://user-images.githubusercontent.com/6977257/100966981-e9017a80-350c-11eb-8baf-9fdea851fda4.png)
Mas se no mesmo momento eu executar `$ make` de novo tudo funciona:
![image](https://user-images.githubusercontent.com/6977257/100967025-ff0f3b00-350c-11eb-96de-9bd5bf8611ec.png)
![image](https://user-images.githubusercontent.com/6977257/100967047-0c2c2a00-350d-11eb-9088-289ce93fc1d0.png)

**Comment by frednora** [comment]
fasm: 
Na primeira imagem mostrou a mensagem. "fasm not found". Significa que precisa instalar o 'fasm' no linux pra compilar o fasm para o gramado. Eu nao havia percebido isso. Vou retirar a compilaçao do fasm do script principal. Obrigado.

**Comment by frednora** [comment]
A ultima imagem mostra o interpretador de comandos do Boot Manager. Se digitar 'boot', vai avançar. Mas tem mais opçoes.

**Comment by frednora** [comment]
Na minha maquina o problema nao aparece porque eu tenho o fasm instalado. Eu retirei essa parte da compilaçao. Poderia tentar novamente, clonando essa nova versao?

**Comment by Jmallone** [comment]
Opa clonei e repeti o mesmo processo e funcionou :+1:
