### ISSUE TITLE
Help: kernel development

### ISSUE THREAD

**Issue by frednora** [frednora/gramado#24]
Kernel development

**Comment by xadaemon** [comment]
Could you detail some things that need doing?

**Comment by Jmallone** [comment]
yes, depending on what it is, i'd like to collaborate too

**Comment by frednora** [comment]
> Could you detail some things that need doing?

The most important thing is the reader/writer synchronization for files just like, sockets, pipes and ttys.
This is all i need to have my ring 3 window server running again.

**Comment by frednora** [comment]
The second most important thing is the virtual console support. Including the tty structure as element of the virtual console structure.   ... just like that.    vc_cons[i].tty->something  ...
