### ISSUE TITLE
fs: Can't open files with only one letter in the extension, ex: file.c

### ISSUE THREAD

**Issue by thaldry** [frednora/gramado#30]
After creating a new file and opening it with gramcode, this appears:
![image](https://user-images.githubusercontent.com/60551465/108145430-2d32fe80-70aa-11eb-9f86-b3e08b8def40.png)

**Comment by frednora** [comment]
Cool :)
Very nice this test. Probably you created a new file using the command interpreter gdeshell.
In this case the command will create an empy file.
But it is not a bug. It is a 'work in progress' ... the function to create new files is very very primitive ... 
See the routines in:  gramado/landos/kernel/0mem/sci/fs/
Thank you.

Another test:
If you open gramcode with no file, so you can type something and save the new file with a standard name for now ... 
this way you can reopen this saved file in the next session. ;)

**Comment by frednora** [comment]
We need to do more tests like this one.
We can create files using the gramcode and using some commands in the command interpreter gdeshell.
We can open these text files using the commnad 'cat'. This way: "$ cat file.txt &" ... 
or we can open the file using the command: "$ gramcode file.txt"

**Comment by frednora** [comment]
It is not bug, because there is nothing to change ... we need to implement more things to improve the support for this kind of operation. The support we have for this is very weak yet.

**Comment by frednora** [comment]
very good, thank you!

**Comment by thaldry** [comment]
Hi! Yes, I created the file using the command 'newfile aa.c' in gdeshell, after that I opened the file with the gramcode. I thought it was a bug because of those characters that appeared on the screen.

**Comment by thaldry** [comment]
Thanks for answering :)

**Comment by frednora** [comment]
> Hi! Yes, I created the file using the command 'newfile aa.c' in gdeshell, after that I opened the file with the gramcode. I thought it was a bug because of those characters that appeared on the screen.

Ohh i'm sorry ... In this special way, it is actually a bug. A bug in the routines for opening files.
It is because there is a problem when we try to open a file named with extension with only one letter. ex: 'file.c' 
 ... it is working better with three letter, like this: 'file.cpp'. :)

**Comment by frednora** [comment]
This is still a work to do in the file system support. That is why im using only .cpp .ini and .txt. hehehe

**Comment by frednora** [comment]
![gramado-root-1](https://user-images.githubusercontent.com/16278453/188940994-c389849e-8e1f-4c7e-8030-cc8204b34b28.png)
See: im still not using .c extention ... we still can't use only one single letter in the extention. In the picture you can see a file called test1.c  ... sometimes im using this file to work in this issue. :)

**Comment by FrancisBFTC** [comment]
Hello Fred! Does this extension bug still exist in the file system? I´m thinking of contributing it...

**Comment by frednora** [comment]
![ext-test](https://github.com/gramado/gramado/assets/16278453/ca18f3a0-21ae-4082-ab40-553572c67b7e)
At this moment the system is able to open files when the filename has an extension with only one letter. And also some different combinations of number of letters. And also support some special 'symbols', just like + - $ etc ...
