### ISSUE TITLE
Help: docs and website

### ISSUE THREAD

**Issue by krthr** [frednora/gramado#4]
Hey! Aquí Wilson. Deberíamos empezar a planear el sitio web y la documentación...

**Comment by frednora** [comment]
Si.

**Comment by juliofederal** [comment]
Ola, eu vi uma mensagem sua no Face solicitando ajuda, gostaria de saber onde eu encontro mais detalhes sobre o projeto. Qual Compilador vc usa, e etc..... entende ??

**Comment by frednora** [comment]
Basicamente: nasm, gcc e ld.
