### ISSUE TITLE
Compilation: Running make

### ISSUE THREAD

**Issue by juniorohanyere** [frednora/gramado#44]
Running make results in lots of warnings and about five errors
![Screenshot_2023-05-05_09_18_29](https://user-images.githubusercontent.com/106378800/236409603-d0339bf6-bef9-4ec5-93fa-3d2ae33ef3f7.png)
![Screenshot_2023-05-05_09_18_18](https://user-images.githubusercontent.com/106378800/236409663-f15b9685-246d-484d-8697-35670c638c1d.png)

**Comment by frednora** [comment]
Ok. Don't care about the warnings ... All the warnings are enabled in the compilation ... this is a part of the debug process.

**Comment by frednora** [comment]
We need the check this multiple definitions of 'heapCount' in stdlib.o. This file is found in the rtl/ library in desktop/ folder. (see the folder apps/client/ for GWS.BIN).

**Comment by juniorohanyere** [comment]
Hi Fred Nora, this issue has been resolved. Thanks
